---
# tasks file for logstash
- name: get key
  ansible.builtin.shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name: install packeges
  apt:
    pkg: apt-transport-https

- name: echo
  ansible.builtin.shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes
    upgrade: yes

- name: logstash install
  apt:
    pkg: logstash
