version: "3.9"

services:
  mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: some_password_of_ur_choice
      MYSQL_DATABASE: name_your_wordpress_database
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_user_password
    volumes:
      - mysql:/var/lib/mysql

  wordpress:
    depends_on:
      - mysql_db
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mysql_db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_user_password
      WORDPRESS_DB_NAME: name_your_wordpress_database
    volumes:
      ["mysite/:/var/www/html"]
  
  webserver:
    image: nginx
    container_name: webserver
    restart: always
    ports:
      - "5555:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
    volumes:
     - mynginx/:/etc/nginx/templates

volumes:
  mysql: {}
  mysite:
  mynginx: