---
# tasks file for update_time
- name: Set timezone to Europe/Minsk
  community.general.timezone:
    name: Europe/Minsk

- name: Install the NTP daemon to synchronize the clocks to ms.
  apt: name=ntp

- name: Make sure ntp is started, and is enabled on restart.
  service: name=ntp state=started enabled=yes

- name: sync cron 1 time at the day
  ansible.builtin.cron:
    name: ntpdate
    minute: "0"
    hour: "0"
    job: "ntpdate 54.155.220.172"
